### ISSUE TITLE
The markup in the document preceding the root element must be well-formed.

### ISSUE THREAD

**Issue by JJSalazar99** [HMS-Core/hms-mapkit-demo#11]
When I synchronized the gradle, it prints all these "Logs"
I have followed the integration steps to the letter and it continues to persist

[
![Captura de pantalla 2020-12-11 023325](https://user-images.githubusercontent.com/49217158/101881091-8ab24880-3b59-11eb-8c5f-7dd321ce7f23.png)
](url)

**Comment by lovehuaweimaps** [comment]
Hello. Please check whether the XML file is correctly configured. If the error persists, provide detailed error information and we will resolve the problem.

**Comment by JJSalazar99** [comment]
Thank you!
The reason for these Warning was the version of the classpath 'com.huawei.agconnect: agcp: 1.4.2.301' and the versions of the HMS libraries that end in 300 or 301
