### ISSUE TITLE
Map is not rendering 

### ISSUE THREAD

**Issue by ramasamy11** [HMS-Core/hms-mapkit-demo#12]
Hi all,

I'm trying to use Huawei maps in react native application for android support, After making necessary changes based on hms map kit demo,  I'm unable to load the maps in Huawei cloud simulator and hms core with google play service devices as well. I'm able to see only a white screen on the map. Please let me know any changes to be done to resolve the issue.  
<img width="562" alt="Screenshot 2020-12-16 at 4 21 49 PM" src="https://user-images.githubusercontent.com/12136368/102447431-f747ae80-4055-11eb-8ecf-984ef41066b2.png">
<img width="562" alt="Screenshot 2020-12-16 at 4 21 49 PM" src="https://user-images.githubusercontent.com/12136368/102447475-0595ca80-4056-11eb-88d5-9da841cbdc59.png">

**Comment by aktug** [comment]
Duplicate https://github.com/HMS-Core/hms-react-native-plugin/issues/53
