### ISSUE TITLE
It does not get the map of China

### ISSUE THREAD

**Issue by guojun21** [HMS-Core/hms-mapkit-demo#14]
it have got every other regions' detailed map, but it just doesn't have the China's detailed map, why?
![Screenshot_20210630_112704_com hdetector](https://user-images.githubusercontent.com/52125056/123898103-4c666480-d997-11eb-885a-71c88be7827b.jpg)
![Screenshot_20210630_112730_com hdetector](https://user-images.githubusercontent.com/52125056/123898107-4ec8be80-d997-11eb-9f53-2292c80a8dcc.jpg)

**Comment by Mike-mei** [comment]
Map Kit does not support China mainland now. You can refer to [supported Countries/Regions](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/supported-countries-and-regions-0000001050160946-V5) for more details.
